### ISSUE TITLE
限制假人在线时间

### ISSUE THREAD

**Issue by lthuas** [engsr6982/LLSE-workspace#17]
希望可以设置放置假人的存在时间，避免玩家一直放置假人不下线导致假人过多引起卡顿，手动挨个计时有点困难，望采纳，感谢作者带来的这么好的插件。
例如假人存在30分钟，每个30分钟后会自动下线

**Comment by engsr6982** [comment]
是统一在线时间，还是自定义每个假人的时间呢？

**Comment by lthuas** [comment]
> 是统一在线时间，还是自定义每个假人的时间呢？

每个假人放置开始单独的喔
