### ISSUE TITLE
iland领地插件与假人问题

### ISSUE THREAD

**Issue by lthuas** [engsr6982/LLSE-workspace#18]
![UI` KBLJ {IGA 9IH8V$6C9](https://github.com/engsr6982/LLSE_Plugins/assets/99377251/a511840c-0f7c-4478-b02c-3ffa8036134e)
（假人在iland保护领地里可以正常破坏，然后和报错）
如果解决比较麻烦的话，可以尝试禁止在领地里放置假人之类的阻止玩家在领地中进行假人操作的行为么
提醒玩家不要在领地放，但是效果不好，还是会有人去放，然后后台就报错...

**Comment by engsr6982** [comment]
不好实现，建议使用事件API自行拦截
