### ISSUE TITLE
无敌不免受掉落伤害

### ISSUE THREAD

**Issue by lthuas** [engsr6982/LLSE-workspace#23]
### 问题插件

TpSystem

### LiteLoader 版本

2.15.0

### BDS 版本

1.20.11

### 发生了什么?

死亡无敌时间不免受掉落带来的伤害，希望可以免除。

### 复现此问题的步骤

1.安装插件，死亡无敌时间设置30秒
2.进入游戏后跳崖进行死亡
3.在30秒无敌时间里再次跳崖，会受到掉落伤害

### 有关的日志/输出

```raw
无日志和报错
```

**Comment by engsr6982** [comment]
无敌时间仅针对返回死亡点的玩家有效，未返回死亡点是没有无敌时间的。 掉落伤害是可以免除的
